### ISSUE TITLE
Sprockets 3.0 support

### ISSUE THREAD

**Issue by Fudoshiki** [ai/autoprefixer-rails#52] opened 2015-02-03 18:54 UTC
```
undefined method `register_postprocessor' for nil:NilClass (NoMethodError)
```

related to https://github.com/sstephenson/sprockets/blob/26d33f08af902b76b65033342d2c07da7eec6372/UPGRADING.md

**Comment by ai** [comment] 2015-02-03 23:48
You mean, that you get this error on Sprockets 3.0?

**Comment by Fudoshiki** [comment] 2015-02-04 02:35
Yes

**Comment by ai** [comment] 2015-02-04 02:37
Right now, specs require some Rails release to test Sprockets 3. Does Rails master uses Sprockets 3?

**Comment by ai** [comment] 2015-02-04 02:41
Because non-Rails usage is low priority I will start it only on next week or later (unfortunately, there  is more high priority open source tasks :( ).

If you need fix sooner, I will accept your PR very fast (even without a tests if Rails master doesn’t use Sprockets 3). I think fix is small. Just a some check and one line for Sprockets 3 and one line for Sprockets 2. You need to fix somwhere in [sprockets.rb](https://github.com/ai/autoprefixer-rails/blob/master/lib/autoprefixer-rails/sprockets.rb).

**Comment by Fudoshiki** [comment] 2015-02-04 05:18
Rails master and rails 4-2-stable branches use sprockets 3.0

**Comment by ai** [comment] 2015-02-04 05:21
So why we haven’t errors in tests?

**Comment by ai** [comment] 2015-02-04 05:22
I understand, because they are doesn’t released yet.

**Comment by ai** [comment] 2015-02-04 05:30
I updated Sprockets to `3.0.0.beta.6` and found only one small issue with YAML. All test are green now: https://travis-ci.org/ai/autoprefixer-rails/builds/49415834

So, it is not a problem with Sprockets 3. Maybe you can post your stacktrace (BTW, it is very bad to miss them in issue reports).

**Comment by gshilin** [comment] 2015-02-04 09:18
Just now I've updated to Sprockets 3.0.0.beta.6 and got the error:
I use ruby 2.2.0p0 and rails 4.2.0

```
rake assets:precompile
rake aborted!
NoMethodError: undefined method `register_postprocessor' for nil:NilClass
baligam/bundler/gems/autoprefixer-rails-dcac5501a790/lib/autoprefixer-rails/sprockets.rb:20:in `install'
baligam/bundler/gems/autoprefixer-rails-dcac5501a790/lib/autoprefixer-rails.rb:18:in `install'
baligam/bundler/gems/autoprefixer-rails-dcac5501a790/lib/autoprefixer-rails/railtie.rb:14:in `block in <class:Railtie>'
railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
railties-4.2.0/lib/rails/initializable.rb:30:in `run'
railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
config/environment.rb:5:in `<top (required)>'
activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
bundler/gems/sprockets-rails-6f787e56c6be/lib/sprockets/rails/task.rb:60:in `block (2 levels) in define'

Tasks: TOP => environment
```

**Comment by ai** [comment] 2015-02-04 09:20
Hm. Problem is not with Sprockets 3. But with this code:

```ruby
      initializer :setup_autoprefixer, group: :all do |app|
        AutoprefixerRails.install(app.assets, *config(app))
      end
```

@gshilin maybe we should run Autoprefixer initializer after some event, when `app.assets` exists?

**Comment by gshilin** [comment] 2015-02-04 09:35
I understand your question, but unfortunately I have no idea what to answer :(

**Comment by ai** [comment] 2015-02-04 09:41
Maybe you know how I can reproduce it? Tests are green.

**Comment by Fudoshiki** [comment] 2015-02-04 09:58
try rails 4.2 in Gemfile

**Comment by Fudoshiki** [comment] 2015-02-04 10:02
source 'https://rubygems.org'

## Rails

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Embed the V8 Javascript Interpreter into Ruby
gem 'therubyracer', platforms: :ruby
# Sprockets Rails integration
gem 'sprockets-rails', github: 'rails/sprockets-rails'

## Basic

gem 'sass', github: 'sass/sass', branch: 'stable'
# Rack-based asset packaging system
gem 'sprockets', '~> 3.0.0.beta.6'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin]

## Assets

# Foundation for Rails http://foundation.zurb.com
gem 'bootstrap-sass', '~> 3.3.1'
# Parse CSS and add vendor prefixes to rules by Can I Use https://twitter.com/autoprefixer
gem 'autoprefixer-rails'
# Rails plugin to conveniently handle multiple models in a single form.
gem 'nested_form'

## Database

# Ruby ODM framework for MongoDB
gem 'mongoid'
# Generates a URL slug/permalink based on fields in a Mongoid-based model
gem 'mongoid-slug'

## Models

# Elasticsearch integrations for ActiveModel/Record and Ruby on Rails
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'elasticsearch-persistence'
# A Scope & Engine based, clean, powerful, customizable and sophisticated paginator for Rails
gem 'kaminari'
# A Ruby gem for on-the-fly processing - suitable for image uploading in Rails
gem 'dragonfly'

## Controllers & views

# Maps controller filters to your resource scopes
gem 'has_scope'
# A set of Rails responders to dry up your application
gem 'responders', '~> 2.0'
# Forms made easy for Rails! It's tied to a simple DSL, with no opinion on markup
gem 'simple_form'
# Kaminari Views for Twitter Bootstrap
gem 'kaminari-bootstrap'
# Easy method to handle logic behind active links
gem 'active_link_to'

## Templates

# Generic interface to multiple Ruby template engines http://github.com/rtomayko/tilt
gem 'tilt', '~> 2.0.1'
# Slim is a template language whose goal is reduce the syntax to the essential parts without becoming cryptic. http://slim-lang.com
gem 'slim', '~> 3.0.1'
# HTML Abstraction Markup Language - A Markup Haiku http://haml.info
gem 'haml'
# Client and Server side Jade template compiler for Rails
gem 'jader'

## Authorization

# Flexible authentication solution for Rails with Warden
gem 'devise'
# Continuation of CanCan, the authorization Gem for Ruby on Rails.
gem 'cancancan', '~> 1.9'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

## Docs

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

## Environments

group :production do
  # Use unicorn as the app server
  gem 'unicorn', platforms: :ruby
  # Real HTTP Caching for Ruby Web Apps
  gem 'rack-cache', require: 'rack/cache'
end

group :development do
  # A very fast & simple Ruby web server http://code.macournoyer.com/thin/
  gem 'thin', platforms: :ruby
  # Use Capistrano for deployment
  gem 'capistrano-rails'
  # Bundler support for Capistrano 3.x
  gem 'capistrano-bundler'
  # RVM support for Capistrano v3
  gem 'capistrano-rvm'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end




rails s
=> Booting Thin
=> Rails 4.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/home/home-user/.rvm/gems/ruby-2.1.5/gems/autoprefixer-rails-5.1.3/lib/autoprefixer-rails/sprockets.rb:20:in `install': undefined method `register_postprocessor' for nil:NilClass (NoMethodError)
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/autoprefixer-rails-5.1.3/lib/autoprefixer-rails.rb:18:in `install'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/autoprefixer-rails-5.1.3/lib/autoprefixer-rails/railtie.rb:12:in `block in <class:Railtie>'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /home/home-user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
  from /home/home-user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  from /home/home-user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
  from /home/home-user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
  from /home/home-user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each'
  from /home/home-user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `call'
  from /home/home-user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
  from /home/home-user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
  from /home/home-user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
  from /home/home-user/repositories/work/kamexpocenter/config/environment.rb:5:in `<top (required)>'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
  from /home/home-user/repositories/work/kamexpocenter/config.ru:3:in `block in <main>'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
  from /home/home-user/repositories/work/kamexpocenter/config.ru:in `new'
  from /home/home-user/repositories/work/kamexpocenter/config.ru:in `<main>'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/server.rb:61:in `app'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/server.rb:139:in `log_to_stdout'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/server.rb:78:in `start'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
  from /home/home-user/repositories/work/kamexpocenter/bin/rails:6:in `require'
  from /home/home-user/repositories/work/kamexpocenter/bin/rails:6:in `<top (required)>'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/client/rails.rb:27:in `load'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/client/rails.rb:27:in `call'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/client/command.rb:7:in `call'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/client.rb:26:in `run'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/bin/spring:48:in `<top (required)>'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/binstub.rb:11:in `load'
  from /home/home-user/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/binstub.rb:11:in `<top (required)>'
  from /home/home-user/repositories/work/kamexpocenter/bin/spring:16:in `require'
  from /home/home-user/repositories/work/kamexpocenter/bin/spring:16:in `<top (required)>'
  from bin/rails:2:in `load'
  from bin/rails:2:in `<main>'

**Comment by ai** [comment] 2015-02-04 10:09
Please, do not post code as text ;) Use `\`\`\`` before and after code.

**Comment by ai** [comment] 2015-02-04 10:10
Can you send PR for a tests?

**Comment by Fudoshiki** [comment] 2015-02-04 11:20
I will try write PR today

**Comment by Fudoshiki** [comment] 2015-02-04 19:56
This isn't autoprefixer-rails issue.
Related to sprockets-rails master branch

**Comment by Fudoshiki** [comment] 2015-02-04 20:08
https://github.com/rails/sprockets-rails/commit/7c48f1b23e25d4b51344bd2aa2d1feb8f57c2b1b

**Comment by josh** [comment] 2015-02-04 20:26
@ai your right, this only affects people running bleeding edge rails/master and sprockets-rails/master. Both of which wont be released as beta for a few months.

Either way, I think I have an idea for a future proof change that will still work on existing code. I'll get a PR open for ya.

**Closed** 2015-02-04 23:44 UTC
